server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: center-service
  profiles:
    active: local
  mvc:
    favicon:
      enabled: false
  jackson:
    # 输出时间为 时间戳
    #    serialization:
    #      write-dates-as-timestamps: true
    # 输出为指定格式字符串
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    execution:
      thread-name-prefix: task-pool-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 2

# Fegin Client
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 60000
        retryer:
          maxAttempts: 3

management:
  endpoint:
    health:
      show-details: always

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.seassoon.center.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level:
    root: INFO
    com.seassoon.center: DEBUG
